email: me@stephenroome.com
title: SFTP Provider forked from danitso (info@danitso.com)
description: >-
  Terraform Provider for SFTP.
github_username: "stephenroome"

highlighter: rouge
markdown: kramdown
plugins:
  - github-pages
remote_theme: pmarsceill/just-the-docs

# Theme settings.
footer_content: 'Fork of Copyright &copy; 2019-2020 <a href="https://stephenroome.com/" target="_blank">Stephen Roome</a> - Distributed under the <a href="https://github.com/stephenroome/terraform-provider-sftpb64/blob/master/LICENSE" target="_blank">Mozilla Public License 2.0</a>'
heading_anchors: true
search_enabled: false
